name: "omiljeni-app"
services: 

  backend: 
    container_name: backent-omilj
    build: ./backend
    env_file:
      - ./env/backend.env
    networks:
      - app_network
    volumes:
      - ./backend:/app
    ports:
      - "${PORT}:5000"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend: 
    container_name: frontend-omilj
    build: ./frontend
    env_file:
      - ./env/frontend.env
    networks:
      - app_network
    volumes:
      - ./frontend:/app
    ports:
      - "${PORT}:3000"
    restart: always
    depends_on:
      - backend


networks:
  app_network:
    driver: bridge